---
abstract: 'Install all modules that provide transactional function'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Tx-Function
requires:
  File::Copy::Undoable: 0
  File::Move::Undoable: 0
  File::Trash::Undoable: 0
  Rinci: 0
  Task::Setup: 0
resources:
  homepage: http://metacpan.org/release/Task-Tx-Function
  repository: http://github.com/sharyanto/perl-Task-Tx-Function
version: 0.02
